name: tests

on:
    push:
    pull_request:
    pull_request_target:
        branches:
            - main
            - master
            - '9.x'
            - '8.x'
            - '7.x'
            - '6.x'
    schedule:
        - cron: '0 0 * * *'

jobs:
#     styling:
#         name: PHP-CS-Fixer
#         runs-on: ubuntu-latest
#         steps:
#         - uses: actions/checkout@v2
#         - name: PHP-CS-Fixer
#           uses: docker://oskarstark/php-cs-fixer-ga
#         - uses: stefanzweifel/git-auto-commit-action@v4
#           with:
#               commit_message: Automatic application of php-cs-fixer changes
    tests:
#         needs:
#             - styling
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.2, 8.3, 8.4, 8.5]
                laravel: [12.*, 13.*]
                stability:
                  - prefer-stable
                # Laravel 13 requires PHP 8.3+.
                exclude:
                    - php: 8.2
                      laravel: 13.*

        name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              run: vendor/bin/phpunit --testdox
